site_name: Sam's Portfolio
site_url: https://sambell2.github.io
site_description: My portfolio to display all of my programming and electronics projects.
site_author: Sam Bell
site_dir: docs/
docs_dir: src/
theme:
  name: cinder
  disable_nav_previous_next: true
  disable_footer: true
plugins:
#  - with-pdf
#  - tags
extra_css:
  - extra/custom.css
markdown_extensions:
  - attr_list
nav:
  - Home: index.md
  - Gallery: gallery.md
#  - Categories: tags.md
  - Programming:
    - Chess Bot: programming/chess_bot.md
    - QR Code Generator: programming/qr_code_generator.md
    - Scripted Journeys: programming/scripted_journeys.md
    - Sudoku Solver: programming/sudoku_solver.md
    - Morse Code Translator: programming/morse_code.md
  - Electronics:
    - CPU:
      - Overview: electronics/cpu/cpu.md
      - Clock Module: electronics/cpu/clock.md
      - ALU: electronics/cpu/alu.md
#    - CPU: electronics/cpu.md
    - Safe: electronics/safe.md
  - Digital Making:
    - Laptop: digital_making/laptop.md
    - Light Fantastic: digital_making/light_fantastic.md
    - Magic Mirror: digital_making/magic_mirror.md
    - Wildlife Camera: digital_making/wildlife_camera.md
  - Robotics:
    - WER 2025: robotics/WER2025.md
    - Picar S: robotics/picar.md
    - CamJam Robot: robotics/camjam.md